
-- +goose Up
-- SQL in section 'Up' is executed when this migration is applied
CREATE TABLE project_descriptions(
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    label VARCHAR(30),
    content TEXT,
    seq SMALLINT,
    created_at TIMESTAMP DEFAULT current_timestamp,
    updated_at TIMESTAMP DEFAULT current_timestamp,
    deleted_at TIMESTAMP
);

-- Seeder
TRUNCATE TABLE project_descriptions;

INSERT INTO project_descriptions (project_id, label, content, seq) VALUES
-- cabe keriting
(1, 'Deskripsi Proyek', 'Cabai keriting adalah buah dari satu jenis tanaman cabai yang panjang dan ramping namun memiliki tekstur keriting. Cabai keriting biasanya berwarna merah, tapi ada juga cabai keriting hijau. Rasanya pedas dan di dalamnya ada butiran sangat kecil tapi sangat keras. Biji cabe keriting yang menghasilkan rasa pedas saat dimakan. <br/><br/> Desa Sukawangi, Bogor, Jawa Barat memiliki potensi penanaman cabe keriting yang sangat besar karena sudah terbukti puluhan tahun bahwa masyarakat setempat menanam komoditas ini dan menghasilkan keuntungan yang cukup besar. Permasalahan saat ini para petani meminjam uang ke tengkulak melalui kesepakatan harga jual yang ditentukan oleh si perantara dengan harga terendah, sehingga biasanya para petani mendapatkan keuntungan yang sangat sedikit dan sering kehilangan uang. Dengan investasi proyek cabai melalui TANIJOY tidak hanya return yang menarik dalam waktu singkat yang bisa didapat, tapi juga bersama - sama kita membantu petani untuk lebih mandiri dalam menjual produknya ke pasar yang lebih menguntungkan', 1),
-- Brokoli
(2, 'Deskripsi Proyek', 'Brokoli dikenal sebagai sayuran hangat dan lezat yang kaya akan puluhan nutrisi. Dikatakan memiliki kandungan nutrisi paling banyak dari setiap sayuran. Ketika kita memikirkan sayuran hijau untuk dimasukkan ke dalam makanan kita, brokoli adalah salah satu sayuran terkemuka yang datang ke pikiran kita. Berasal dari keluarga kubis, brokoli bisa dikategorikan sebagai tanaman hijau yang dapat dimakan. Penyebab komoditi ini bisa dimakan dan membuat Anda sehat, produk ini selalu dibutuhkan di pasaran.<br/><br/>Desa Sukawangi, Bogor, Jawa Barat memiliki potensi besar untuk menanam brokoli. Telah terbukti selama beberapa dekade, di mana orang selalu menanam komoditas ini sebagai tanaman perantara dan mendapatkan keuntungan besar dari penjualan. Namun, masalah yang terjadi saat ini petani meminjam uang ke tengkulak melalui kesepakatan harga jual yang ditentukan oleh perantara dengan harga terendah. Biasanya petani mendapatkan keuntungan sangat sedikit dan bahkan sering kehilangan uang. Melalui investasi proyek brokoli oleh TANIJOY, tidak hanya imbal hasil yang menarik dalam waktu singkat dapat diperoleh, tapi juga bersama-sama kita membantu petani untuk lebih mandiri dalam menjual produknya ke pasar yang lebih menguntungkan.', 1),
-- Daun Bawang
(3, 'Deskripsi Proyek', 'Daun Bawang (Allium  fistulosum  L.) adalah bagian tanaman yang dapat dimakan adalah seikat selubung daun yang terkadang keliru disebut tangkai atau tangkai. Ini tumbuh luas di iklim tropis atau subtropis. Daun bawang bisa tumbuh di dataran rendah atau dataran tinggi dengan ketinggian 250 - 1500 meter di atas permukaan laut. Selain itu, kawasan ini memiliki curah hujan  150 - 200 mm / tahun dan suhu harian 18 - 25°C sangat sesuai untuk  pertumbuhan  tanaman daun bawang. Sayuran ini memiliki banyak kegunaan karena bisa dimakan  mentah dan dimasak dalam berbagai salad juga merupakan pelengkap rasa masakan lainnya, oleh karena itu permintaannya cukup besar.<br/><br/>Desa Sukawangi, Bogor, Jawa Barat memiliki potensi besar menanam daun bawang. Telah terbukti selama beberapa dekade, di mana orang selalu menanam komoditas ini sebagai tanaman perantara dan mendapatkan keuntungan besar dari penjualan. Namun, masalah yang terjadi saat ini petani meminjam uang ke tengkulak  melalui kesepakatan harga jual yang ditentukan oleh perantara dengan harga terendah. Biasanya petani mendapatkan keuntungan sangat sedikit dan bahkan sering kehilangan uang. Melalui investasi proyek daun bawang oleh TANIJOY, tidak hanya imbal hasil yang menarik dalam waktu singkat dapat diperoleh, namun juga bersama - sama, kami membantu petani untuk lebih mandiri dalam menjual produknya ke pasar yang lebih menguntungkan.', 1),
-- Kacang Kapri
(4, 'Deskripsi Proyek', 'Kacang Kapri termasuk dalam keluarga polong - polongan. Tanaman kacang kapri dapat ditanam pada dataran tinggi dan dataran rendah, namun lebih optimal apabila di tanam di dataran tinggi. Tanaman kacang kapri dapat mulai dipanen pada 70 - 90 hari setelah tanam. Kacang kapri banyak ditemui di supermarket ataupun pasar tradisional dan memiliki nilai jual yang cukup tinggi terutama kacang kapri manis. Pasar dari jenis ini cukup banyak terutama restoran dan hotel.<br/><br/>Beberapa petani di Desa Sukawangi sudah memulai menanam tanaman Kacang Kapri sejak 5 tahun yang lalu. Karena sebelumnya para petani pernah menanam buncis, mereka tidak mengalami kesulitan dalam membudidaya kacang kapri. Bandung. Permintaan untuk sayuran jenis ini cukup tinggi dan cenderung konstan karena selain pasar, restoran dan hotel biasanya menggunakan sayuran ini sebagai salah satu menu wajibnya. Beberapa dari petani juga ada yang sudah memulai menanam secara organik, karena permintaan sayuran organik juga cukup tinggi. Tantangan dari budidaya kacang kapri ini adalah hama serangga dan tenaga panen yang khusus.<br/><br/>Dengan penanaman kacang kapri secara terorganisir, harapannya petani sayur di desa Sukawangi dapat mensuplai secara kontinu kebutuhan sayur - sayuran dari kota Jakarta, Bogor dan Bandung.', 1),
-- Pak Choy 
(5, 'Deskripsi Proyek', 'Pak choy adalah salah satu tanaman yang termasuk dalam famili Brassicaea atau sawi - sawian. Pangkal tanaman pak choy biasanya tebal dan ini yang menjadi ciri khas dari sayuran ini. Pak choy dapat ditanam di daerah dataran tinggi maupun rendah. Beberapa petani ada juga yang menggunakan teknologi hidroponik untuk menanam sayuran ini. Pak choy termasuk tanaman sayuran yang dapat dipanen dalam waktu singkat, yaitu 20 - 40 Hari. Pak choy bisa dipanen dalam umur yang masih muda yaitu 20 - 30 hari dan biasanya memiliki harga jual yang lebih mahal. Pak choy yang di panen cepat ini biasa kita sebut baby pak choy. Sayuran pak choy banyak ditemui di supermarket dan pasar tradisional. Permintaan dari sayuran ini cukup tinggi terutama yang organik.<br/><br/>Desa Sukawangi Bogor telah bertahun - tahun menanam jenis sawi - sawian termasuk pak choy dan secara rutin menyuplai sayuran untuk pasar di Jakarta dan Bandung. Permintaan untuk sayuran jenis ini cukup tinggi dan cenderung konstan karena selain pasar, restoran dan hotel biasanya menggunakan sayuran ini sebagai salah satu menu wajibnya. Beberapa dari petani juga ada yang sudah memulai menanam secara organik, karena permintaan sayuran organik juga cukup tinggi. Tantangan dari budidaya pak choy adalah hama serangga dan juga intensitas hujan yang terlalu tinggi. Petani binaan kami menggunakan jebakan serangga menggunakan hormon pemikat agar hama tidak menyerang tanaman utama.<br/><br/>Budidaya Pak choy dilakukan secara berkelanjutan sehingga komoditas selalu tersedia dan dapat di supply rutin ke pasar, supermarket dan restoran tanpa melalui tangan tengkulak. Dengan berinvestasi ke petani pak choy melalui tanijoy merupakan salah satu investasi yang cukup menarik, karena selain waktunya yang cukup singkat, investor juga bisa mendapatkan potensi keuntungan yang cukup tinggi. Dalam proyek pak choy selama 3 bulan ini petani dapat melakukan pemanenan sebanyak 2 - 3 kali.', 1),
-- Sawi Putih
(6, 'Deskripsi Proyek', 'Sawi Putih atau petsai adalah salah satu tanaman yang termasuk dalam famili Brassicaea atau sawi - sawian. Sawi putih idealnya di tanam di daerah dataran tinggi dengan ketinggian diatas 900 mdpl dan suhu 19 - 21 °C. Sawi putih termasuk tanaman sayuran yang dapat dipanen dalam waktu singkat, yaitu 30  - 60 Hari tergantung pada varietasnya. Sawi putih banyak ditemui di pasar tradisional maupun supermarket. Sayuran ini banyak digemari oleh masyarakat terutama sebagai salah satu bahan untuk membuat cap cay.<br/><br/>Desa Sukawangi Bogor telah bertahun - tahun menanam jenis sawi - sawian termasuk sawi putih dan secara rutin menyuplai sayuran untuk pasar di Jakarta dan Bandung. Permintaan untuk sayuran jenis ini cukup tinggi dan cenderung konstan karena selain pasar, restoran dan hotel biasanya menggunakan sayuran ini sebagai salah satu menu wajibnya. Tantangan dari budidaya tanaman sawi ini adalah curah hujan yang terlalu tinggi atau banjir di lahan dapat menyebabkan busuk. Namun petani binaan kami sudah memiliki beberapa mitigasi untuk setiap resiko yang akan dihadapi seperti salah satunya meninggikan bedengan tanaman.<br/><br/>Budidaya sawi putih ini dilakukan secara berkelanjutan sehingga komoditas selalu tersedia dan dapat di supply rutin ke pasar, supermarket dan restoran tanpa melalui tangan tengkulak. Dengan berinvestasi ke petani sawi melalui tanijoy merupakan salah satu investasi yang cukup menarik, karena selain waktunya yang cukup singkat, investor juga bisa mendapatkan potensi keuntungan yang cukup tinggi, tergantung pada harga pasar ketika panen.', 1);


-- +goose Down
-- SQL section 'Down' is executed when this migration is rolled back
DROP TABLE project_descriptions;